# Generated by Django 6.1.1 on 2026-09-10 18:19

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='nome de exibição')),
                ('bio', models.TextField(blank=True, verbose_name='biografia')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=users.models.profile_picture_path, verbose_name='foto de perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('main_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='posts.category', verbose_name='tema principal')),
                ('profile_tags', models.ManyToManyField(blank=True, related_name='profiles', to='posts.tag', verbose_name='tags do perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
